[tool.poetry]
name = "currency-quote"
version = "0.1.0"
description = ""
authors = ["Luiz Longo <longo.luizh@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[tool.poetry.group.dev.dependencies]
bumpver = "^2023.1121"
pytest = "^7.3.1"
black = {extras = ["d"], version = "^23.3.0"}
tox = "^4.5.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.bumpver]
current_version = "0.1.0"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "Bump version {old_version} -> {new_version}"
commit = true
tag = true
push = false

[tool.bumpver.file_patterns]
"pyproject.toml" = ['current_version = "{version}"', 'version = "{version}"']

[tool.black]
line-length = 120
target-version = ['py310']
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.hg
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
  | */install-poetry.py
)
'''
