# Generated by Django 4.2.1 on 2023-05-15 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("representation", models.CharField(max_length=3)),
                ("symbol", models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name="RateQuote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("rate_value", models.DecimalField(decimal_places=16, max_digits=20)),
                (
                    "base_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="base_currency",
                        to="currencies.currency",
                    ),
                ),
                (
                    "rate_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rate_currency",
                        to="currencies.currency",
                    ),
                ),
            ],
        ),
    ]
